---
image: Visual Studio 2019
skip_commits:
  files:
    - "bin/**"
    - "*.md"
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - appveyor DownloadFile https://rubygems.org/gems/rubygems-update-3.3.26.gem
  - gem install --local rubygems-update-3.3.26.gem
  #- gem update --system
  - gem --version
  - bundle install
build: off
test_script:
  - bundle exec rake ci
environment:
  matrix:
    - ruby_version: "200"
